# Define accompanying passwords/secrets in group_vars/development/vault.yml
laravel_apps:
  wwc.co.uk:
    site_hosts:
      - canonical: wwc.test
        redirects:
          - www.wwc.test
    local_path: ../wwc # path targeting app directory (relative to Ansible root)
    ssl:
      enabled: false
      provider: self-signed
    env:
      app_debug: true