disable_default_pool: true

php_extensions_default:
  - php7.3-bcmath
  - php7.3-cli
  - php7.3-common
  - php7.3-curl
  - php7.3-dev
  - php7.3-fpm
  - php7.3-gd
  - php7.3-intl
  - php7.3-mbstring
  - php7.3-mysql
  - php7.3-pgsql
  - php7.3-readline
  - php7.3-soap
  - php7.3-xml
  - php7.3-zip

php_error_reporting: 'E_ALL & ~E_DEPRECATED & ~E_STRICT'
php_display_errors: 'Off'
php_display_startup_errors: 'Off'
php_max_execution_time: 120
php_max_input_time: 300
php_max_input_vars: 1000
php_memory_limit: 512M
php_mysqlnd_collect_memory_statistics: 'Off'
php_post_max_size: 25M
php_sendmail_path: /usr/sbin/ssmtp -t
php_session_save_path: /tmp
php_session_cookie_httponly: 'On'
php_session_cookie_secure: 'Off'
php_upload_max_filesize: 25M
php_track_errors: 'Off'
php_timezone: '{{ ntp_timezone }}'

php_opcache_enable: 1
php_opcache_enable_cli: 1
php_opcache_fast_shutdown: 1
php_opcache_interned_strings_buffer: 8
php_opcache_max_accelerated_files: 4000
php_opcache_memory_consumption: 128
php_opcache_revalidate_freq: 60
