- name: composer
  src: geerlingguy.composer
  version: 1.6.1

- name: ntp
  src: geerlingguy.ntp
  version: 1.5.2

- name: logrotate
  src: nickhammond.logrotate
  version: e7a498d

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.3

- name: redis
  src: DavidWittman.redis
  version: 1.2.5