laravel_env_defaults:
  app_name: Example
  app_env: "{{ env }}"
  app_debug: false
  app_url: https://example.com
  log_channel: stack
  db_connection: mysql
  db_host: localhost # override this in group_vars/environment/laravel_apps.yml
  db_port: 3306
  db_database: "{{ site | underscore }}_{{ env }}"
  db_username: "{{ site | underscore }}"
  broadcast_driver: log
  cache_driver: redis
  session_driver: redis
  queue_driver: redis
  redis_host: 127.0.0.1 # override this in group_vars/environment/laravel_apps.yml
  redis_password: "{{ vault_redis_password }}"
  redis_port: 6379
  mail_driver: smtp
  mail_host: smtp.mailtrap.io
  mail_port: 2525
  mail_user: null
  mail_password: null
  mail_encryption: null
  # pusher_app_id: 
  # pusher_app_key: 
  # pusher_app_secret:
  # pusher_app_cluster: mt1
  # mix_pusher_app_key:"${PUSHER_APP_KEY}"
  # mix_pusher_app_cluster:"${PUSHER_APP_CLUSTER}"

site_env: "{{ laravel_env_defaults | combine(project.env | default({}), vault_laravel_apps[site].env) }}"